package com.example.filemanager;

import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.net.Uri;import android.os.storage.*;import android.view.*;import android.widget.*;import androidx.documentfile.provider.DocumentFile;import java.io.*;import java.util.*;

public class MainActivity extends Activity{
 LinearLayout body; android.content.SharedPreferences p; static final int PICK=77;
 int dp(int n){return(int)(n*getResources().getDisplayMetrics().density+.5f);}
 TextView t(String s,int z){TextView v=new TextView(this);v.setText(s);v.setTextSize(z);v.setPadding(dp(16),dp(10),dp(16),dp(10));return v;}
 public void onCreate(Bundle b){super.onCreate(b);p=getSharedPreferences("storage",0);home();}
 void home(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setPadding(dp(12),dp(10),dp(12),dp(10));TextView h=t("ניהול אחסון",24);h.setTypeface(null,1);r.addView(h,new LinearLayout.LayoutParams(-1,dp(60)));body=new LinearLayout(this);body.setOrientation(LinearLayout.VERTICAL);ScrollView s=new ScrollView(this);s.addView(body);r.addView(s,new LinearLayout.LayoutParams(-1,0,1));setContentView(r);render();}
 void render(){body.removeAllViews();String target=p.getString("target","internal");body.addView(t("יעד ברירת מחדל לקבצים חדשים",18));body.addView(t("נוכחי: "+(target.equals("internal")?"אחסון פנימי":"כרטיס SD / אחסון חיצוני"),16));
 Button in=new Button(this);in.setText("💾 אחסון פנימי");in.setOnClickListener(v->{p.edit().putString("target","internal").remove("tree").apply();render();});body.addView(in);
 Button sd=new Button(this);sd.setText("💳 בחר כרטיס SD / חיצוני");sd.setOnClickListener(v->pick());body.addView(sd);
 Button test=new Button(this);test.setText("✍️ צור קובץ ביעד הנבחר");test.setOnClickListener(v->writeTest());body.addView(test);
 body.addView(t("אמצעי אחסון",19));for(StorageVolume v:vols()){body.addView(t("• "+(v.isRemovable()?"חיצוני":"פנימי")+"\n"+label(v)+"\nמצב: "+v.getState(),15));if(v.isRemovable()){Button e=new Button(this);e.setText("⏏️ הוצאה בטוחה");e.setOnClickListener(x->rootCmd("unmount",v));body.addView(e);Button m=new Button(this);m.setText("🔌 טעינה מחדש");m.setOnClickListener(x->rootCmd("mount",v));body.addView(m);}}}
 ArrayList<StorageVolume> vols(){ArrayList<StorageVolume>a=new ArrayList<>();StorageManager m=(StorageManager)getSystemService(STORAGE_SERVICE);a.addAll(m.getStorageVolumes());return a;}
 String label(StorageVolume v){String u=v.getUuid();return (u==null?"כונן":u)+" — "+(v.getDirectory()==null?"":v.getDirectory().getAbsolutePath());}
 void pick(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT_TREE);i.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_PERSISTABLE_URI_PERMISSION);startActivityForResult(i,PICK);}
 protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q==PICK&&r==RESULT_OK&&d!=null){Uri u=d.getData();try{getContentResolver().takePersistableUriPermission(u,d.getFlags()&(Intent.FLAG_GRANT_READ_URI_PERMISSION|Intent.FLAG_GRANT_WRITE_URI_PERMISSION));}catch(Exception e){}p.edit().putString("target","external").putString("tree",u.toString()).apply();render();}}
 void writeTest(){try{String x=p.getString("tree",null);DocumentFile d=x==null?DocumentFile.fromFile(getFilesDir()):DocumentFile.fromTreeUri(this,Uri.parse(x));DocumentFile f=d.createFile("text/plain","StorageTest.txt");OutputStream o=getContentResolver().openOutputStream(f.getUri());o.write(("נוצר "+new Date()).getBytes("UTF-8"));o.close();Toast.makeText(this,"נוצר קובץ ביעד שנבחר",Toast.LENGTH_LONG).show();}catch(Exception e){Toast.makeText(this,"כתיבה נכשלה: "+e.getMessage(),Toast.LENGTH_LONG).show();}}
 void rootCmd(String a,StorageVolume v){String u=v.getUuid();if(u==null){Toast.makeText(this,"אין UUID לכונן",Toast.LENGTH_LONG).show();return;}new Thread(()->{try{java.lang.Process q=Runtime.getRuntime().exec(new String[]{"su","-c","sm "+a+" "+u});int c=q.waitFor();runOnUiThread(()->new AlertDialog.Builder(this).setTitle(a.equals("unmount")?"הוצאה":"טעינה").setMessage("Root הסתיים. קוד: "+c).setPositiveButton("אישור",null).show());}catch(Exception e){runOnUiThread(()->Toast.makeText(this,"Root לא זמין: "+e.getMessage(),Toast.LENGTH_LONG).show());}}).start();}
}